package database

var migrations = []string{
	`CREATE TABLE IF NOT EXISTS roles (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		name TEXT NOT NULL UNIQUE
	)`,
	`CREATE TABLE IF NOT EXISTS users (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		login TEXT NOT NULL UNIQUE,
		password TEXT NOT NULL,
		last_name TEXT,
		first_name TEXT,
		patronymic TEXT,
		role_id INTEGER NOT NULL REFERENCES roles(id) ON DELETE RESTRICT
	)`,
	`CREATE TABLE IF NOT EXISTS categories (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		name TEXT NOT NULL UNIQUE
	)`,
	`CREATE TABLE IF NOT EXISTS manufacturers (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		name TEXT NOT NULL UNIQUE
	)`,
	`CREATE TABLE IF NOT EXISTS suppliers (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		name TEXT NOT NULL UNIQUE
	)`,
	`CREATE TABLE IF NOT EXISTS units (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		name TEXT NOT NULL UNIQUE
	)`,
	`CREATE TABLE IF NOT EXISTS products (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		article TEXT NOT NULL UNIQUE,
		name TEXT NOT NULL,
		description TEXT,
		price REAL NOT NULL CHECK(price >= 0),
		discount REAL NOT NULL DEFAULT 0 CHECK(discount >= 0),
		quantity INTEGER NOT NULL DEFAULT 0 CHECK(quantity >= 0),
		image TEXT,
		category_id INTEGER NOT NULL REFERENCES categories(id) ON DELETE RESTRICT,
		manufacturer_id INTEGER NOT NULL REFERENCES manufacturers(id) ON DELETE RESTRICT,
		supplier_id INTEGER NOT NULL REFERENCES suppliers(id) ON DELETE RESTRICT,
		unit_id INTEGER NOT NULL REFERENCES units(id) ON DELETE RESTRICT
	)`,
	`CREATE TABLE IF NOT EXISTS order_statuses (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		name TEXT NOT NULL UNIQUE
	)`,
	`CREATE TABLE IF NOT EXISTS pickup_points (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		address TEXT NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS orders (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		order_date TEXT,
		delivery_date TEXT,
		pickup_code TEXT,
		status_id INTEGER NOT NULL REFERENCES order_statuses(id) ON DELETE RESTRICT,
		pickup_point_id INTEGER NOT NULL REFERENCES pickup_points(id) ON DELETE RESTRICT,
		user_id INTEGER REFERENCES users(id) ON DELETE RESTRICT
	)`,
	`CREATE TABLE IF NOT EXISTS order_items (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
		product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
		quantity INTEGER NOT NULL CHECK(quantity > 0)
	)`,
}
